config/routes.rb
Metrics::Application.routes.draw do
  resources :metrics
  root :to => "metrics#show"
  match '/json' => "metrics#json"

end

app/models/metric.rb
class Metric < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController

  # GET /metrics
  # GET /metrics.json
  def show
    @metrics = Metric.find(:all, :order => "created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @metrics }
    end
  end
		
  def json
   @metrics = Metric.find(:all, :order => "created_at DESC")
   #render :text => @users.inspect
   #@json = JSON.generate(@users)
   #render :text => "hi"
   render :json=> @metrics.to_json
  end

  def index
   @metrics = Metric.find(:all, :order => "created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.csv  # index.csv.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metrics</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/metrics/_form.html.erb
<%= form_for(@metric) do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Status_id %><br />
    <%= f.text_field :Status_id %>
  </div>
  <div class="field">
    <%= f.label :Text %><br />
    <%= f.text_field :Text %>
  </div>
  <div class="field">
    <%= f.label :Accounts_Used %><br />
    <%= f.text_field :Accounts_Used %>
  </div>
  <div class="field">
    <%= f.label :Followers_Count %><br />
    <%= f.text_field :Followers_Count %>
  </div>
  <div class="field">
    <%= f.label :Time %><br />
    <%= f.text_field :Time %>
  </div>
  <div class="field">
    <%= f.label :Failures %><br />
    <%= f.number_field :Failures %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metrics/edit.html.erb
<h1>Editing metric</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric %> |
<%= link_to 'Back', metrics_path %>

app/views/metrics/index.csv.erb
<% headers = ["Status Id", "Text", "Accounts used","Followers Count","Time Taken(in milliseconds)","Failures","Creation Time"] %>
<%= CSV.generate_line(headers, {:row_sep => nil}).html_safe %>
<% @metrics.each do |m| %>
<% row = [ m.Status_id,m.Text,m.Accounts_Used,m.Followers_Count,m.Time,m.Failures,m.created_at ] %>
<%= CSV.generate_line(row, {:row_sep => nil}).html_safe %>
<% end %>

app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= render 'form' %>

<%= link_to 'Back', metrics_path %>

app/views/metrics/show.html.erb
<h1 align="center">Listing metrics</h1>
<h3 align="center"><%= link_to "Export to CSV", :controller => "metrics", :action => "index", :format => :csv %></h3><br/>
<!-- <%= link_to " csv", "/csv",request.parameters.merge({:format => "csv"})%>-->
<table border="1" width="100%" class="altrowstable" id="alternatecolor">
  <tr>
    <th><u>Status Ids</u></th>
    <th><u>Text</u></th>
    <th><u>Accounts used</u></th>
    <th><u>Followers count</u></th>
    <th><u>Time Taken(in millisec)</u></th>
    <th><u>Failures</u></th>
    <th><u>Created at</u></th>
  </tr>

<% @metrics.each do |metric| %>
  <tr>
    <td><%= metric.Status_id %></td>
    <td><%= metric.Text %></td>
    <td><%= metric.Accounts_Used %></td>
    <td><%= metric.Followers_Count %></td>
    <td><%= metric.Time %></td>
    <td><%= metric.Failures %></td>
    <td><%= metric.created_at %></td>
  </tr>
<% end %>
</table>

<br />